version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build Solution
          command: cd ~/repo/src && dotnet build
workflows:
  version: 2
  default:
    jobs:
      - build